[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mirror_pipeline"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.14.3",
    "torch==2.10.0",
    "datasets==4.3.0",
    "dotenv==0.9.9",
    "jaxtyping==0.3.3",
    "jsonargparse==4.42.0",
    "lightning==2.5.5",
    "transformers==5.10.0",
    "typed-datasets @ git+https://github.com/Plyb/typed-datasets.git",
    "tqdm==4.67.1",
    "matplotlib==3.10.9",
    "wandb",
    "jupyterlab==4.5.10",
    "ipykernel==7.2.0",
]

[dependency-groups]
dev = ["pyright"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
mirror = ["templates/*.jinja"]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
